#-------------------------------
# General Site Settings
title: Glass of Numbers
logo: glassofnumbers_whitebg.jpg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Wilson
  image: face_logo.jpg
  say-hello: Hello, I’m <strong>Wilson</strong>
  bio: Hello everyone! I make videos to help people learn math more easily! Please work together with me and make math education available to students and children by subscribing to <a href="https://www.youtube.com/glassofnumbers" target="_blank">my YouTube channel</a>. Thank you!


#-------------------------------
# Contact links
twitter: https://twitter.com/glassofnumbers # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/glassofnumbers # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e